/* 
 * File:   pattern_index.h
 * Author: njin
 *
 * Created on October 10, 2009, 7:04 PM
 */

#ifndef _PATTERN_INDEX_H
#define	_PATTERN_INDEX_H

#include <set>
#include <string>
#include <vector>
using namespace std;

//class: pattern_index
/*to keep track of the codes of subgraph patterns that have been generated before
 in order to avoid repetitive consideration of the same subgraph pattern*/
class pattern_index {
public:
    set<vector<short> > data;	/*the code of each subgraph pattern is stored as vector<short>,
								 here "data" keeps track of the codes of all subgraph patterns 
								 that have been generated by the algorithm*/
    void insert(vector<short>& s);	/*insert a code "s" into "data"*/
    bool find(vector<short>& s);	/*find out if code "s" is already in "data"*/
};

#endif	/* _PATTERN_INDEX_H */

